### ISSUE TITLE
Git setup: always create merge commits?

### ISSUE THREAD

**Issue by robmoss** [robmoss/git-is-my-lab-book#16]
By default, `git` enables fast-forward merges, which update the branch pointer to match the merged branch, and do not create merge commits.

Should we instruct the reader to set `merge.ff` to `no` so that `git merge` **always** creates merge commits? This would ensure that the revision history identifies all branch merges, by avoiding fast-forward merges.

**Comment by EamonConway** [comment]
Now that you bring this up, I think that setting `merge.ff` to `no` is good idea. Especially as we are very much highlighting collaboration as well. Just ensures complete transparency.

**Comment by robmoss** [comment]
Alright, I'll add that to the instructions and create a new pull request shortly :smile:
