### ISSUE TITLE
Error in pushing new branch

### ISSUE THREAD

**Issue by jaycrick** [robmoss/git-is-my-lab-book#62]
```
$ git push -u origin
fatal: The current branch my-new-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream my-new-branch merge2
```

git push -u origin my-new-branch may work

**Comment by robmoss** [comment]
Thanks for the bug report. Can you please confirm what version of git is installed? I can't reproduce this with git 2.34.1.

**Comment by robmoss** [comment]
Ahh, wait, this depends on the value of `push.default`; with the default setting (`simple`) "you need to configure an upstream branch with the same name" ([docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault)). I have it set to `current`, which doesn't require this step.

**Comment by jaycrick** [comment]
Thanks Rob, is that something you changed? I'm just using git out of the box, don't think I have changed any settings.

**Comment by robmoss** [comment]
It's not the default setting, so I changed it (many years ago, as far as I can tell).
